version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: amen:latest
    depends_on:
      - 'db'
    ports:
      - "3003:3003"
    networks:
      - webnet
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - 3306:3306
  #   # volumes:
  #   # - "/home/docker/data:/data"
  #   # deploy:
  #   #   placement:
  #   #     constraints: [node.role == manager]
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #   networks:
      - webnet

networks:
  webnet: